#!/bin/bash
# docker-dns-daemon
# chkconfig: 345 20 80
# description: docker-dns-daemon
# processname: docker-dns-daemon

DAEMON_PATH="/usr/local/docker/docker-dns-daemon"

DAEMON=docker-dns-daemon
CONFIGFILE="/etc/artegic/docker-dns.conf"
NAME="docker-dns-daemon"
DESC="Dynamic DNS Updates on Docker Events"
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/docker-dns-daemon.`date +%F`.log
DAEMONOPTS="-d -c $CONFIGFILE -p $PIDFILE -l $LOGFILE"
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
        $DAEMON $DAEMONOPTS > /dev/null 2>&1
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
